### PR TITLE
Omkar submission: Compared SVM and 3-layer ANN on Titanic dataset

### PR DESCRIPTION
**Pull request by omjadhav85**
Submission
Compared SVM and 3-layer ANN on Titanic dataset

### CODE REVIEW

**Comment by bLAckBLAZER** [comment]
Compared SVM and 3-layer ANN on Titanic dataset

**Comment by AtharvaJ10** [comment]
There are 2 affiliations of yours. Please erase one. The last date of submission is 9th September 2019.

**Comment by omjadhav85** [comment]
I did not get you sir. What should I do exactly?

**Comment by AtharvaJ10** [comment]
There are 2 affiliations in your paper. Both are your affiliations. Erase one

**Comment by omjadhav85** [comment]
No sir, I did it in collaboration with my friend. The two names are Omkar
Jadhav(me) and Omkar Masurekar

**Comment by AtharvaJ10** [comment]
Oh. I didn't see that. Thanks

**Pull request merged**
