### PR TITLE
Shobhit submission: My_proj

### PR DESCRIPTION
**Pull request by shobhitsrivastava-ds**

### CODE REVIEW

**Comment by harshbansal1999** [comment]
Please provide the conclusion at end and also mention about your code
analysis like data preparation,model evaluation

Best regards
Harsh Bansal
AITS Peer Committee Member

**Comment by shobhitsrivastava-ds** [comment]
Made the necessary changes.

**Comment by shobhitsrivastava-ds** [comment]
Made changes related to conclusion.

**Comment by shobhitsrivastava-ds** [comment]
Made the changes

**Pull request merged**
